### PR TITLE
Adds ability to calculate standard deviation for randomread and randomwrite ops

### PR DESCRIPTION
**Pull request by keesturam**
I believe this should fix https://github.com/cloud-bulldozer/snafu/issues/180
@acalhounRH ?

### CODE REVIEW

**Comment by acalhounRH** [comment]
@bengland2 The original code does calculate the standard deviation. fio_analyzer is paired with fio_wrapper such that after all test have ran it evaluates std-dev as you have stated. 

The original code did accomplish randread and randwrite evaluation, the if statement is valid if read/write was present in the operation field (read/write/randwrite/randread). This code is just explicit checking for randread or randwrite. With this version of code the read and write checks will still be valid and the extra randread/randwrite if statements will never be invoked. 

The only limitation that this code has is that it does not process rw, 

rw, readwrite

Mixed sequential reads and writes. 

if the user is not seeing the randread or randwrite std-dev data in elasticsearch or Grafana I can work with them 1-on-1.

**Comment by acalhounRH** [comment]
Recommend closing PR unless it is changed to only add sequential read/write operation.

**Comment by jtaleric** [comment]
@bengland2 @acalhounRH Can we close this since it seems unnecessary (based on Alex's latest comment)?

**Comment by bengland2** [comment]
@keesturam  this is getting stale, we should either cancel this or go forward, can you discuss with Alex in next couple of days if you really need this or we'll  close it?  I lost track of this one, sorry  -ben

**Comment by keesturam** [comment]
Closing the PR based on Alex's inputs.

**Pull request closed without merging**
