### PR TITLE
Smf statvfs

### PR DESCRIPTION
**Pull request by bengland2**
this PR includes a new top-level module that gathers filesystem statistics about any POSIX filesystem given a pathname.   The smallfile wrapper calls this to gather info about space and inodes used after a test completes.   This will be used by fs-drift also and could be used by other storage-related benchmarks.   For example, you can see whether the filesystem is filled up or near filled up after a test.

### CODE REVIEW

**Comment by bengland2** [comment]
@dustinblack does this make sense to you?   @acalhounRH ?

**Comment by aakarshg** [comment]
@acalhounRH @dustinblack are you okay with this PR?

**Comment by aakarshg** [comment]
> @acalhounRH @dustinblack are you okay with this PR?

looking to merge this once i get a go ahead from one of you

**Comment by aakarshg** [comment]
@bengland2 can you please rebase this so that the CI can run ?

**Comment by bengland2** [comment]
so the only test that failed was hammerdb and this is why:
```
...
++ grep 'SEQUENCE COMPLETE'
Error from server (BadRequest): container "hammerdb" in pod "hammerdb-workload-8b14ce1d-ncwtm" is waiting to start: trying and failing to pull image
++ echo 'Hammerdb test: Success'
...
+ python3 ci/check_es.py -s marquez.perf.lab.eng.rdu2.redhat.com -p 9200 -u 8b14ce1d-0490-575b-b73f-f22fa2b80525 -i ripsaw-hammerdb-results
No result found in ES
...
```
Seems to have nothing to do with this PR.  Can we merge?

**Pull request merged**
