### PR TITLE
added function to add KiB io size to all analyzed documents.

### PR DESCRIPTION
**Pull request by acalhounRH**
This is needed to better graph data in Grafana

### CODE REVIEW

**Comment by aakarshg** [comment]
added @dustinblack to review, since you've knowledge of units in fio.

**Comment by acalhounRH** [comment]
Will update to handle MB as well, what would be the handling for kb_base?

**Comment by acalhounRH** [comment]
Updated to handle edge case of switching kb_base value from 1000 to/from 1024. and handling of IEC and non-IEC values.

**Comment by aakarshg** [comment]
@acalhounRH this needs a  rebase.

**Comment by dry923** [comment]
@acalhounRH can you rebase this or would you rather close and open a new one when you get back to it?

**Comment by jtaleric** [comment]
@dry923 @aakarshg i suggest if we don't hear anything today (Feb 18th) .We close, Alex might be busy with other things ATM.

**Comment by aakarshg** [comment]
> @dry923 @aakarshg i suggest if we don't hear anything today (Feb 18th) .We close, Alex might be busy with other things ATM.

agreed closing this out for now.

**Pull request closed without merging**
