### PR TITLE
Skip TLS cert verify

### PR DESCRIPTION
**Pull request by rsevilla87**
Add mechanism to skip TLS certificate verify step.

### CODE REVIEW

**Comment by jtaleric** [comment]
I am alright with this change. However it isn't a *fix* for #312

**Comment by rsevilla87** [comment]
> LGTM, and I'm approving because we need a fix quickly, but... would be nice if default was to NOT verify cert.

Yeah, I know. With this code, verifying cert assumes ES is exposed over a TLS endpoint. The reason behind setting it to off by default is that it would break CI since we don't have a TLS exposed ES.

**Comment by aakarshg** [comment]
> Add mechanism to skip TLS certificate verify step. This PR can help to fix [cloud-bulldozer/ripsaw#312](https://github.com/cloud-bulldozer/ripsaw/issues/312)

This description will still close the issue, just a fyi.

**Pull request merged**
