### PR TITLE
Add debugging tools

### PR DESCRIPTION
**Pull request by rsevilla87**
Add some debugging tools to containers.  Container size is only increased by 29MiB.

```
STEP 6: RUN dnf install -y --nodocs procps-ng iproute net-tools ethtool nmap iputils                                   
Updating Subscription Management repositories.                                                                         
Unable to read consumer identity                                                                                       
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.        
Last metadata expiration check: 0:01:17 ago on Wed Mar  4 12:10:03 2020.                                                                                                                                                                      
Dependencies resolved.                                                                                                                                                                                                                        
================================================================================                                       
 Package      Arch      Version                        Repository          Size                                        
================================================================================                                       
Installing:                                                                                                            
 iproute      x86_64    4.18.0-15.el8                  ubi-8-baseos       616 k                                                                                                                                                               
 iputils      x86_64    20180629-2.el8                 ubi-8-baseos       149 k                                        
 ethtool      x86_64    2:5.0-2.el8                    ubi-8-baseos       151 k                                        
 procps-ng    x86_64    3.3.15-1.el8                   ubi-8-baseos       328 k                                                                                                                                                               
 net-tools    x86_64    2.0-0.51.20160912git.el8       ubi-8-baseos       323 k                                        
 nmap         x86_64    2:7.70-5.el8                   ubi-8-appstream    5.8 M                                                                                                                                                               
Installing dependencies:                                                                                                                                                                                                                      
 libmnl       x86_64    1.0.4-6.el8                    ubi-8-baseos        30 k                                                                                                                                                               
 nmap-ncat    x86_64    2:7.70-5.el8                   ubi-8-appstream    237 k                                                                                                                                                               
                                                                                                                       
Transaction Summary                                                                                                    
================================================================================                                       
Install  8 Packages                                                                                                                                                                                                                           
                                                                                                                       
Total download size: 7.6 M                                                                                                                                                                                                                    
Installed size: 29 M
```

### CODE REVIEW

**Comment by dry923** [comment]
ycsb failed because it ran out of space on the minikube system. i'll add more.

**Comment by rsevilla87** [comment]
@jtaleric This would force us to have extra tests on that tags, thus extra complexity and maintenance efforts.
As the container image hasn't grown very much so far. IMHO I think we would avoid having two tags for now, in the future we can put it back on the table if further tools are needed.

**Pull request merged**
