### PR TITLE
Migrate ycsb to ubi8 & python3

### PR DESCRIPTION
**Pull request by rsevilla87**
Migrate ycsb to ubi8 & python3,
YCSB is not python3 ready yet so we execute it with python2.
Improved logging as well.

### CODE REVIEW

**Comment by rsevilla87** [comment]
Fixes https://github.com/cloud-bulldozer/snafu/issues/103

**Comment by aakarshg** [comment]
ok to test

**Comment by rsevilla87** [comment]
@aakarshg miss some labels here ;)

**Pull request merged**
