### PR TITLE
Normalize UUID and user args

### PR DESCRIPTION
**Pull request by rsevilla87**
Depends-On: 332

### CODE REVIEW

**Comment by bengland2** [comment]
overall I appreciate the idea of refactoring to maximize common code and user experience, but I have same question that Joe had, why is uuid an env var?   It is autogenerated by ripsaw isn't it?   I think this is for the best if we standardize on how to identify a test, otherwise it becomes very difficult to write things like touchstone.

**Comment by rsevilla87** [comment]
Yeah, that's the idea. UUID and user is automatically set from ripsaw but these variables might not be present in cases outside from ripsaw.

There are other variables like `clustername`, which we get from env vars.

This is just an effort to standardize the way we pass variables to snafu wrappers, so I'm open to suggestions.
 
@bengland2 can you explain with more what do you mean with "how to identify the test"?

**Comment by rsevilla87** [comment]
My idea is to make a series of PR in order to add more granularity to the changes

**Comment by bengland2** [comment]
are you talking about the idea of running snafu outside of ripsaw?    Because that's a very important discussion but I see no reason why test uuids couldn't be generated in the same way for that case -- the method of deploying workload generators might be different, but the way results appear in elastic search would ideally be the same.

**Comment by rsevilla87** [comment]
> are you talking about the idea of running snafu outside of ripsaw? Because that's a very important discussion but I see no reason why test uuids couldn't be generated in the same way for that case -- the method of deploying workload generators might be different, but the way results appear in elastic search would ideally be the same.

The existing problem now is that some arguments are passed from the CLI itself and others from environment variables depending on the test.

**Comment by bengland2** [comment]
oh, in that case why would people want to pass IN the UUID, as opposed to getting it returned to them?   If you leave it up to the user, how do you know they won't pass the same UUID in twice, defeating its uniqueness?   Don't trust the users, I am one, I should know ;-)

**Comment by jtaleric** [comment]
> oh, in that case why would people want to pass IN the UUID, as opposed to getting it returned to them? If you leave it up to the user, how do you know they won't pass the same UUID in twice, defeating its uniqueness? Don't trust the users, I am one, I should know ;-)

Ah, the reason for passing "in" the UUID is to have a single UUID that is tagged from our result data to our metadata... Now, could we instead of a list of UUIDs which represent a single run, possibly.

**Pull request closed without merging**
